linters:
  enable:
    - gofmt
    - goimports
    - unused
    - staticcheck
    - unconvert
    - revive
    - ineffassign
    - vet
    - unused
    - misspell
  disable:
    - errcheck

run:
  tests: false
  timeout: 8m
