apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-node-decorator.rbacName" . }}
  labels:
    {{- include "k8s-node-decorator.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
