apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-node-decorator
  labels:
    app: k8s-node-decorator
spec:
  selector:
    matchLabels:
      app: k8s-node-decorator
  template:
    metadata:
      labels:
        app: k8s-node-decorator
    spec:
      hostNetwork: true
      serviceAccount: k8s-node-decorator-account
      containers:
      - name: my-container
        image: zliangatakamai/k8s-node-decorator:v0.1.0
        args: ["--poll-interval=30"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
