apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-decorator-clusterrole
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "update", "patch"]
