name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  go-build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Build
      run: make build

    - name: Test
      run: go test -v ./...

  go-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: make lint


  build-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: make docker-build
